### ISSUE TITLE
Dynamically Load Stylesheet at runtime

### ISSUE THREAD

**Issue by GobbaFish** [tombenner/nui#189]
Hi,

What is the best method to load an existing stylesheet at runtime? This method would have to be called in response to a user action. Or should I simply be overwriting the file  using [NUISettings setAutoUpdatePath:@"/Users/myusername/projects/ios/MyApp/Style.nss"];

**Comment by timbodeit** [comment]
You can use `+[NUIRenderer changeStylesheet:]` to load a different stylesheet at runtime.
