### ISSUE TITLE
Exclude subviews in View doesn't work properly

### ISSUE THREAD

**Issue by elbelga** [tombenner/nui#224]
Hi, when I add some classes to exclude-subviews in View style, the style is always applied. Example 

    View {
        exclude-subviews: UISwitch,UILabel;
        background-image: NUIViewBackground.png;
    }

I believe that the problem is in the category NUI/UI/UIView+NUI.m, you need to replace this

    NSMutableArray *excludeSubviews = [NSMutableArray arrayWithArray:[[NUISettings get:@"exclude-subviews" withClass:value] componentsSeparatedByString:@","]];

by 

    NSMutableArray *excludeSubviews = [NSMutableArray arrayWithArray:[[NUISettings get:@"exclude-subviews" withClass:value] componentsSeparatedByString:@" , "]];

I added two spaces in separator.

**Comment by timbodeit** [comment]
Fixed by #312.
