### ISSUE TITLE
add #import to the README

### ISSUE THREAD

**Issue by Hitokun** [tombenner/nui#225]
I know it is pretty simple stuff, but in the README.md you never tell people to #import <NUISettings.h>. Don't know if it has to do with my setup or what, but I just lost an hour with this and a lot of rookies will be lost too.

Also, you never explain properly how to add CoreParse to the project, so again, it leave the kids alone in the woods.

Just my little share in making the project more usable for begginers.

Keep th egood job

**Comment by timbodeit** [comment]
Installation instructions are now part of the readme.
Import instructions for Swift are also given.

About importing header files: everyone of us started out as a rookie. And if someone approaches me with a specific question, I'm happy to help.
I would prefer however to keep the Readme as concise as possible. In my opinion, it should provide everything that a reasonably skilled developer needs to use the library.
Covering basic things that are explained in the first chapters of any book about iOS development is not a part of that.
