### ISSUE TITLE
Issue with NUI

### ISSUE THREAD

**Issue by rossbc** [tombenner/nui#231]
I found the NUI project and its EXACTLY what I need. I am trying to install it and am having some serious issues - its been almost a day now. 

I must apologize - I am an IOS newbie, so perhaps the install instructions are my issue. I downloaded and extracted the ZIP of your code, then copied the NUI folder into my project folder and added it to my project (add files). 

So far so good. I then tried to add the CoreParse project in as a subproject. I downloaded and extracted the code to a folder, and added it as a subproject by dragging its xcodeproj file into my project (found this on StackOverflow). I had issues with the CPgrammar class categories; they would not work properly. I tried combining the categories into the parent class and that worked, but it just pushed the errors I was getting further down into the code. The next issue came with a category of NSSet, so I was at a dead end since my workaround could not be done with that.

Then I started over and tried just adding all the CoreParse code into my project without using the subproject method. This worked better, but now I have an error in the NUIDefinition class - it crashes while being called from the CPShiftReduceParser.parse function - line 172 after loading the 3rd or 4th line of the default NSS file. I get a EXC_BAD_ACCESS, code=1 error and everything just stops.

I am able to see it looping through the lines in the NSS file, just not sure what is causing it to die. Any kind of help I can get in resolving this would be greatly appreciated.

**Comment by Wenzhi** [comment]
I think you might need to add "-ObjC" to "Other Linker Flag" in the build settings?

**Comment by timbodeit** [comment]
Closing this, as its not actually an issue with NUI and has been inactive for a while.
If you need further help setting up NUI, feel free to ask.

**Comment by subaMmackowski** [comment]
I am getting this error too. "NUIDefinition class - it crashes while being called from the CPShiftReduceParser.parse function - line 172 after loading the 3rd or 4th line of the default NSS file. I get a EXC_BAD_ACCESS, code=1 error and everything just stops."

I didn't use CocoaPods and I can't use CocoaPods due to the nature of my project.  I did not have any trouble adding NUIParse to the project.
