### ISSUE TITLE
NUI as a static library

### ISSUE THREAD

**Issue by kylesmyth** [tombenner/nui#243]
I'm hoping to build and compile NUI as a static library to eventually bind to in Xamarin.iOS.

Right now I'm having issues linking the CoreParse library as a subproject. I'm getting the error: 
target specifies product type 'com.apple.product-type.framework', but there's no such product type for the 'iphoneos' platform

Would it be possible to build a universal NUI library with Cocoapods?

**Comment by PabloLerma** [comment]
NUI can be now generated as a static library so I think we can close this issue. 
@timbodeit ?
