### ISSUE TITLE
where's the proper place to apply custom nui settings?

### ISSUE THREAD

**Issue by AaronYi** [tombenner/nui#245]
If I have custom nui settings items, what's the proper way to use them in the project?
I'm overriding - (void)applyNUI in my custom view, is that right?

**Comment by PabloLerma** [comment]
Could we close this issue?
@timbodeit 

P.s.: If I disturb you too much, if you want I could not tag you :P

**Comment by Stunner** [comment]
Both him and I are watchers on the project so we would see any activity occurring in the project irregardless. :smile:

**Comment by PabloLerma** [comment]
Ohh okay! Good to know :smiley:

**Comment by Stunner** [comment]
Don't close this as this is something I am working on. It can be found on the [override-feature](https://github.com/Stunner/nui/tree/override-feature) branch in my fork.

**Comment by Stunner** [comment]
#317 should take care of this.
