### ISSUE TITLE
When UIButton's view hierarchy changes with button state change, style not re-applied

### ISSUE THREAD

**Issue by glentregoning** [tombenner/nui#267]
When the default state has no background-color set, UIButton adds a UIImageView for a custom background color when changing from default state to selected state. 

This causes a problem as the NUI style is only applied once, not on button state change. 

As a result, the corner radius does not get applied to the selected state background image. 

Example:

my-custom-button {
  corner-radius: 14px;
  border-width: 1px;
  border-color: white;
  background-color-selected: #ffffff;
}

Default State (no / transparent background):
![screen shot 2014-08-07 at 1 26 57 pm](https://cloud.githubusercontent.com/assets/1776494/3848549/5369637e-1e71-11e4-9dc9-1b4e3a315cd6.png)

Selected State:
![screen shot 2014-08-07 at 1 27 32 pm](https://cloud.githubusercontent.com/assets/1776494/3848551/5757932a-1e71-11e4-82a5-069765c7d81c.png)

**Comment by PabloLerma** [comment]
Is this issue solved since it seems so by reference #268

**Comment by Stunner** [comment]
You are right. Thanks @PabloLerma.
