### ISSUE TITLE
Tint color?

### ISSUE THREAD

**Issue by markst** [tombenner/nui#272]
Since iOS7 it's possible to set the tint color of views.
Is it possible to define the global tint color and of certain views?

**Comment by frapaa** [comment]
You can set global tint color programatically with `[[UIApplication sharedApplication] keyWindow].tintColor = [Color redColor]`

Unfortunately, there's no way to load a specific color from the stylesheet, but you could add a class

```
ThemeColors {
    tint-color: #FF0000;
}
```
Then use ``[[UIApplication sharedApplication] keyWindow].tintColor = [NUISettings getColor:@"tint-color" withClass:@"ThemeColors"]`

**Comment by timbodeit** [comment]
Duplicate of #223.
