### ISSUE TITLE
UILabel Kerning

### ISSUE THREAD

**Issue by imton** [tombenner/nui#279]
````obj-c

#import "UILabel+TextKerning.h"

@implementation UILabel (TextKerning)

-(void) setText:(NSString *)text withKerning:(CGFloat)kerning
{
    if ([self respondsToSelector:@selector(setAttributedText:)])
    {
        NSMutableAttributedString *attributedString = [[NSMutableAttributedString alloc] initWithString:text];
        [attributedString addAttribute:NSKernAttributeName
                                 value:[NSNumber numberWithFloat:kerning]
                                 range:NSMakeRange(0, [text length])];
        [self setAttributedText:attributedString];
    }
    else{
        [self setText:text];
    }
}

-(void) setKerning:(CGFloat)kerning
{
    [self setText:self.text withKerning:kerning];
}

@end
````

**Comment by Stunner** [comment]
Can you elaborate on this issue? It is not evident what you are trying to convey from your code. Closing for now, feel free to reopen when providing additional information.

**Comment by Stunner** [comment]
After looking at other issues opened by @imton, it appears that these are intended at suggestions of adding functionality. Confusing as one would expect this sort of thing to be submitted via pull request. Reopening for the time being pending further investigation.

**Comment by timbodeit** [comment]
@Stunner This does not look like an odd form of a pull request to me.
Rather like a collection of code snippets on how to make random stuff work on UIViews without any relation to NUI.

A request that NUI should offer a Kerning on labels would be valid. Help with its implementation would be extremely appreciated. But I'm not going to be guessing what someone is trying to tell me with a code snippet only issue.

Closing for the same reason as #283.
Feel free to reopen once you have provided more details on your specific issue and how it relates to nui.
