### ISSUE TITLE
AutoLayout and View Hierarchy

### ISSUE THREAD

**Issue by ben95beng** [tombenner/nui#284]
Does this library work with AutoLayout? Or does it have issues?
- Also, is it possible to specify hierarchy like in css? this could be specifying Class of ancestors or nuiClass of ancestors.

**Comment by PabloLerma** [comment]
Hi @ben95beng,

NUI works perfectly with autolayout since it does not get involved with it. NUI styles are applied when the views are added to the view hierarchy and then autolayout is applied.

You can specify hierarchy as you can see in the README: https://github.com/tombenner/nui#setting-an-elements-style-class-programmatically

**Comment by PabloLerma** [comment]
Thanks for closing @timbodeit ! :+1: 
Shouldn't we make a good clean in the PR and issues?

**Comment by timbodeit** [comment]
@PabloLerma 
I'll be going over the pull requests in the upcoming weeks.
As a start I'm working on getting the additional test coverage from #293 merged. Once that's done I'll work through the remaining PRs.

About the issues: In my opinion, we shouldn't prematurely close legitimate issues, just to get the issue count down. 
Any help in finding duplicate, already fixed or or question-only issues would be highly appreciated though 😉

Side note: You don't happen to have a working iOS 7 Simulator installed, do you?

**Comment by PabloLerma** [comment]
Nice!

Yeah, I agree with you. I'll try to help you and comment in some issues that I think should be closed.

I don't have a iOS 7 Simulator but a co-worker have it. How could we help you?

**Comment by timbodeit** [comment]
If you could check out the iOS7 reference images branch and run the unit tests on a @1x (like iPad 2) and @2x (iPhone 5) simulator under iOS 7, that would be awesome. 

There should be 4 new png files in the git working copy. 
Please push these 4 files somewhere on github or send them to me.

**Comment by PabloLerma** [comment]
Hi @timbodeit ,
The tests "testsSetFontName" and "testsSetFontSize" in NUIButtonRendererBackgroundColorTests are not working. If I am not wrong, TestTheme.NUI.nss has "font-name: ultraLightSystem" but it is never get applied because UIFontWeightBlack condition in NUISettings.m (UIFontWeightBlack availability is >8.2).

**Comment by timbodeit** [comment]
What Xcode version and deployment target are you using?
The ones I have in the Travis matrix all seam to handle it fine: https://travis-ci.org/tombenner/nui/builds/91818076

I'll look into it though.

**Comment by timbodeit** [comment]
Fixed in d91d1c7.
Were the PNG files generated when you ran the test suite?

**Comment by PabloLerma** [comment]
Two of them. The other two no because the test failed but I will try again tomorrow if you want.



—

**Comment by timbodeit** [comment]
Did you run them on both simulators?
It should be two per simulator (4 in total).
These two test failures shouldn't have anything to do with it.

**Comment by PabloLerma** [comment]
Ouch! Only on iPad 2. Tomorrow I will generate them for you, sorry for the trouble!



—

**Comment by timbodeit** [comment]
Perfect. Thank you 👍

**Comment by PabloLerma** [comment]
I've never attached images here, @timbodeit check if it is okay:

<img width="80" alt="testbuttonwithgradient_ios7 2x" src="https://cloud.githubusercontent.com/assets/871250/11265745/21292800-8e9f-11e5-81d4-798c76a88c4d.png">
<img width="100" alt="testsegmentedcontrolcolorsrendercorrectly_ios7 2x" src="https://cloud.githubusercontent.com/assets/871250/11265746/21420672-8e9f-11e5-8b49-e9a59dc16a2a.png">
![testbuttonwithgradient_ios7](https://cloud.githubusercontent.com/assets/871250/11265748/21450e9e-8e9f-11e5-8eff-72ae5be018ac.png)
![testsegmentedcontrolcolorsrendercorrectly_ios7](https://cloud.githubusercontent.com/assets/871250/11265747/2143a77a-8e9f-11e5-9719-9fdb1117f26b.png)
