### ISSUE TITLE
alternating row attributes in tableview

### ISSUE THREAD

**Issue by wdcurry** [tombenner/nui#285]
Is there anything within NUI to address this goal? We can do it of course within cell creation, but it would be awesome to declaratively set it up at app level via NUI.

**Comment by PabloLerma** [comment]
You can't at the moment but it could be possible if you set different NUI classes in cellForRow.

**Comment by timbodeit** [comment]
If you want full control, every other row would need a different class if we're not going to duplicate every single attribute.

Doing that inside your `cellForRowAtIndexPath` is reasonably easy:
```
cell.nuiClass = indexPath.row % 2 ? "FooClass" : "BarClass";
```

Moving this logic into the nui framework wouldn't even make your own code any shorter.

To avoid feature creep, I'm voting to close this issue.
@Stunner Your thoughts on this?

**Comment by Stunner** [comment]
I think this issue can be closed. @timbodeit illustrated how this issue would be resolved from the host app's code, and it appears to be the appropriate way to handle this issue.
