### ISSUE TITLE
Please update the podspec after fixing breaking changes

### ISSUE THREAD

**Issue by Wenzhi** [tombenner/nui#290]
The latest release is 0.5.4, which is release a year ago.

In the new Xcode 6.2, NUI had the msg_send issue and is fixed. But the version on Cocoapods is still the broken one. 

Please update the podspec and push it up to cocoapods so we don't have to make the podfile pointing to a specific commit.

**Comment by phatmann** [comment]
@tombenner, can you please add me as a co-owner to the pod? Then I can push it. Or alternately you can push it. 

I made the release and tag already (0.5.5) and updated the Podspec.

**Comment by Wenzhi** [comment]
Thank you for acting so fast! Closing the issue~

**Comment by phatmann** [comment]
Reopening, because @tombenner has not pushed 0.5.5 to CocoaPods yet

**Comment by phatmann** [comment]
0.5.5 is pushed
