### ISSUE TITLE
NUI with Swift?

### ISSUE THREAD

**Issue by tobinharris** [tombenner/nui#291]
Hi folks

Has anyone got NUI working with Swift and CocoaPods? 

If I include this in my Bridging Header

    #import <NUI/NUISettings.h>

I'm getting a `Could not build module NUI`

Any help appreciated.

t

**Comment by dfoerderreuther** [comment]
Hi, 

I'm using it with swift and CocoaPods. My steps briefly:

Podfile: 

    ..
    pod 'NUI'
    ..

pod install
Bridging-Header:

    ..
    #import <NUI/NUISettings.h>
    ..

Theme.nss

    Label {
       font-color: #FF0000;
    }

AppDelegate.swift

    ...
    NUISettings.initWithStylesheet("Theme")
    ...

Cheers, 
Dominik

**Comment by tobinharris** [comment]
Thanks Dominik. 

I'm trying out Classy but may just give this another go, see if I can get it to build.

Tobin

**Comment by raf1hh** [comment]
Running into the same issue with helloworld swift app:

TestCocoaPods/Pods/NUI/NUI/Core/Parser/NUIDeclaration.h
TestCocoaPods/Pods/NUI/NUI/Core/Parser/NUIDeclaration.h:9:9: 'NUIParse.h' file not found
TestCocoaPods/bridging-header.h
TestCocoaPods/bridging-header.h:15:9: Could not build module 'NUI'

**Comment by Selendri** [comment]
Hi, 
I'm using it with swift and CocoaPods too. I followed dfoerderreuther's steps.
However, I have got the same issue as tobinharris and raf1hh : `Could not build module 'NUI` etc.
Could you explain me how you resolved this issue? 
Thanks in advance. 
Regards

**Comment by diogo10** [comment]
Hello, I got the same error....please somene can people us ?

**Comment by atsepkov** [comment]
Same, would really like to see this resolved. `pod install` worked fine and adding the import to project's header file causes the same error as others report (further investigating it reveals that it's due to NUIParse.h not being found, I do see it in the Pods repo, however).

**Comment by peantunes** [comment]
Same problem here. Any updates about this problem?

**Comment by atsepkov** [comment]
I actually ended up switching to Classy instead. There are a couple issues (mainly with enums) but it works seamlessly with Swift for the most part.

**Comment by peantunes** [comment]
I have create a fork with a solution for this problem. The solution was to change all the imports from "NUIParser.h" to <NUIParser/NUIParser.h>
You can use pointing the cocoapods to my repository. https://github.com/peantunes/nui

**Comment by drbarto** [comment]
Are there any plans to integrate those changes in the main repo as well? The fork is outdated, so using it is not a real option in the long run.

**Comment by timbodeit** [comment]
@drbarto The current nui master should work fine with Swift. Let me know if you're running into any issues.

**Comment by drbarto** [comment]
@timbodeit I'm using NUI via Cocoapods. Using the last pod release like this: `pod 'NUI'` does not work (yielding the same errors as described in this issue).
But indeed -- the current head version does work: `pod 'NUI', :head` So I'll use this until the next  release. Thanks!

**Comment by timbodeit** [comment]
Usage with Swift was fixed in #307.
Hopefully we'll find the time for a 0.6.0 release soon.

Have a look at [the milestone](https://github.com/tombenner/nui/milestones/0.6.0) for more details.

**Comment by osvadimos** [comment]
Hi All, as suggested https://github.com/CocoaPods/CocoaPods/issues/2303 
 1. I've closed xcode
 2. Ran 'pod install''
 3. Open xcode
 Build succeeded.
