### ISSUE TITLE
change UITextField border colour failed

### ISSUE THREAD

**Issue by nimingzhe** [tombenner/nui#294]
I want to change UITextField's border colour. But it doesn't work.

TextField{
border-color:#438aca;
border-width=1;
border-style=line;
}

**Comment by MaksimVialykh** [comment]
You have some mistakes is syntax,

Try it ->
TextField {
     border-color: #438aca;
     border-width: 1;
     border-style: line;
}

You can see examples on nui/NUI/Themes/ folder or open this link https://github.com/MaksimVialykh/nui/blob/master/NUI/Themes/Blue.NUI.nss
