### ISSUE TITLE
Setting nuiClass outside of init does not work?

### ISSUE THREAD

**Issue by SteveNewhouse** [tombenner/nui#295]
I'm setting nuiClass for a UILabel subclass and noticing that it is not applying the styles unless I do so inside the init function.  So this does not work:

    class StatusLabel : UILabel  {
		required init(coder aDecoder: NSCoder) {
			super.init(coder: aDecoder)

			/* This DOES work */
			self.nuiClass = "MyLabel:MyChildStyle"
		}
	
		/* Calling this from the instantiating class does NOT work... */
		func configure()  {
			self.nuiClass = "MyLabel:MyChildStyle"
		}
    }   

I've tried adding `setNeedsDisplay` but that did not work.  Any ideas?

**Comment by PabloLerma** [comment]
Hi @SteveNewhouse! I think it is because how NUI works. If you change the nuiClass in configure(), when the UILabel has been already drawn it is not going to work as you already said. 
Try to render the label manually like this:
```objectivec
    [NUILabelRenderer render:self withClass:@"MyLabel:MyChildStyle"];
```

**Comment by SteveNewhouse** [comment]
Yes, you are right.. that works.  Thank you!
