### ISSUE TITLE
Unable to ignore: UIImagePickerController

### ISSUE THREAD

**Issue by SteveNewhouse** [tombenner/nui#300]
There does not seem to be a way to not apply the Button NUI style to the buttons within the UIImagePickerController.

It would appear the only way is to avoid using Button as a class altogether?  Anyone know a good solution here?  I do not want the buttons in this screenshot to take on any style at all:

![image](https://cloud.githubusercontent.com/assets/1760211/8378732/6a7636b6-1be9-11e5-9a5f-baf5a4b0b703.png)

**Comment by timbodeit** [comment]
Couldn't you solve this using [exclude-subviews](https://github.com/tombenner/nui#excluding-views-from-nuis-styling)?

**Comment by SteveNewhouse** [comment]
I can now that the comma-separation issue is fixed... I also discovered that, as it turns out, presenting a UIImagePickerController does not actually put a UIImagePickerController into the view hierarchy, but rather a bunch of other things like PUCollectionView and (the one pictured above) PLCropOverlay... finding the right one of those views to exclude-subviews from was the key.
