### ISSUE TITLE
Manually rendering.

### ISSUE THREAD

**Issue by sdkdimon** [tombenner/nui#332]
Hi, how can i prevent automatically UI style rendering for whole iOS UI components, and apply render manually on those components that i needed ? My solution is at NUISettings  setGlobalExclusions for all UI, and use NUIRenderer.

**Comment by Stunner** [comment]
Please see [this comment of mine](https://github.com/tombenner/nui/issues/323#issuecomment-187657680).

**Comment by sdkdimon** [comment]
As I understand, the solution is define styles with names, that do not match  with UI classes names? Right?
For example: 
```
CUSTOM_BUTTON {
    background-color: #FFFFFF;
    font-color: #E6E6E6;;
    font-name: AppleGothic;
    font-size: 18;
}
```
And than render style with renderer manually
```
[NUIRenderer renderButton:_button withClass:@"CUSTOM_BUTTON"];
```

**Comment by Stunner** [comment]
You got the first part correct, the second part is where you are mistaken. Please consult this [walkthrough to get you up and running with NUI](http://h4ckish.com/2015/12/31/how-to-style-your-ios-app-with-nui/).

**Comment by sdkdimon** [comment]
I guess for second part instead of usage of NUIRenderer i need just setup NuiClass like this.
```
[_button setNuiClass:@"CUSTOM_BUTTON"];
```
And if view already at window hierarchy then i need call applyNUI.
 ```
[_button applyNUI];
```

**Comment by Stunner** [comment]
Yeah, but in my experience I haven't had to call `applyNUI` but your mileage may vary.

**Comment by sdkdimon** [comment]
Thanks.
