### ISSUE TITLE
Install with CocoaPods Failed.

### ISSUE THREAD

**Issue by 460122775** [tombenner/nui#353]
Install with CocoaPods Failed.
when use pod 'NUI' in podfile, and after it install success,  then i got an error while building the project.

Error:
ld: library not found for -lNUI
clang: error: linker command failed with exit code 1 (use -v to see invocation)

So i download the demo named 'NUIDemo', and modify its podfile and add 'NUI' pod, and after it install success,  then i got the same error.

I can`t solve this problem after i searching and trying for a long time...
What happened to this lib???

**Comment by timbodeit** [comment]
Can you provide a minimal example project to reproduce this? Which Cocoapods version are you using?
I just created a new project and added NUI to the Podfile. Builds as expected.

**Comment by 460122775** [comment]
Okay, I just tried to create a new blank project, and get success.

It should be my project get the wrong config with somewhere, thanks a lot for answer my question, and I will post the solution after I run my project with NUI successfully.

With best wishes !

**Comment by 460122775** [comment]
I got the result...

In config of my targets -> Build Settings -> Search Paths -> Library Search Paths.
it is lack of "$PODS_CONFIGURATION_BUILD_DIR/NUIParse" and "$PODS_CONFIGURATION_BUILD_DIR/NUI" 

After i added them, i got success.

But, why cocoapods didn't finish config it only in my project...
