### ISSUE TITLE
Make property nuiClass IBInspectable

### ISSUE THREAD

**Issue by Emailrus** [tombenner/nui#363]
`@property (nonatomic, retain) IBInspectable NSString* nuiClass;`
So it will be a bit easier to set nui class in IB

**Comment by Stunner** [comment]
This has already been accepted and is available on HEAD of the master branch.

**Comment by Emailrus** [comment]
Oh, 106 commits since release, didn't notice that. Ok then, will wait for next release

**Comment by Stunner** [comment]
No need to wait. You can point CocoaPods to pull from head, which is what I currently do.

**Comment by Emailrus** [comment]
I would rather have stable version, rather picking up any changes that might come from head
