### ISSUE TITLE
Not works with swift3

### ISSUE THREAD

**Issue by razalur** [tombenner/nui#374]
Hello! I moved my project from swift 2.3 to swift 3. And now nui do not works. Neither via storyboard nui field nor via nuiClass in code with apply method.
Don't know what to do. It's critical for me, because all styles in my app defined by nui. Could you please to help me?

**Comment by razalur** [comment]
Sorry, that's ok

**Comment by Stunner** [comment]
@razalur Could you please explain how you overcame your issue so that others with your same issue may benefit?

**Comment by razalur** [comment]
Yes. The trouble was trivial and not related to nui at all. It was wrong path to nss file. So the styles could not by applied. So be careful to avoid such situation! )
